spring:
  datasource:
    url: jdbc:mysql://217.61.97.245:3306/ged?createDatabaseIfNotExist=true
    username: ged
    password: ged
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL8Dialect
      ##hibernate.format_sql: true


